language: java
jdk: openjdk8
services:
    - docker
env:
    global:
    - PROJECT_VERSION=0.0.2
    - secure: GalbdSICTw2YFlOzX9htOfrRrfTmsNjvAnv7FM+QU8x2Ozz+DClo2eKnGPzQGiVLoqkIMpz65wB96He21Nsc8LBlzGd6pMu63Xgn9V6K5T6ujsDe7AmJEcUIHUD45VKMN9dz3rvQDchI1rLVRSARsctxzV78BJv8IcMfjD7e0h5OXlADvFQDdt8DDQ1pPpRKg/lPm6vNVs5p1n+8onfxNYqgvpbCG8BUTxYcQqrrF+BnJ0jDLtlADocflEkzsXeFtJ/Ye2SlXl/8dixQ1Qi2jdiOZNSe+InsNBLHgVb0oknJSglUbPWVKcjcebaRUkbL1xTrkO9YL57rcq7fCcWHJ7fvfIt3QmaZ3cX3RdO8gKeHx7m8sQcc6g67vAs5ftc+86UuZu3ZykCrWrrHlNoZZ6x/qWsGikYhF5qZk2u9Kdha4ppZ3jQ2DKnDAnakCN/yT8BWMqsnj2JCZ+eVDUukV00fNT1PH/GO5dvR+55Q2GOBqg+YvY5rdFZxeVq63OurmE2vAChtDSu465Zej4hgEDOMNFeaC/Jhv+YTQPqTlOFIBzveHqN1rFxZ8vNI70BinlIBNspsbtGD9mJ2WQjCNvp2m1phOqdWlalUZ7nUk4+d+8ei+CUkReuHL104jnuIiv2A6Cp0/Du2Sa9qkLY9jarri57SlGemhLkqRAh7Z0A=
    - secure: IrlPGkkUGVmwuor7TAADIjGPmfZwXtXDtwEdGgSC5yFy1UaYDwUq42dkqGSrlSIz7BUCIR4cldu03u/wCSRuOgZlVFTkpxOQOE6L1BIfLNbOkiagjXpORyVpLQCo7+IZwCKjNNoVfVxw0UfLosrtbEJ2v8yqL8fDyAOvA/42v5cww0s+ZMPevXDAnSRapNSzLXGSHVfbnSyELWJ+dBb0ewWCcSz37vpCeZiJUPFXP4hUkzBAKLsSkJNklkPDSs+sZPzyhCNIsoQ0KWuNPnCp3mMFAMBTQLohexY07BP47najRxmNPuqp9f06Nk7I/vvY+xF74e7UiSYkYtW2I3dxs79gM0V8FA3bAMfYz/Q8d4eS1uwQ2iOSM0pqFSTtXn4ybriMigq9TUVah76sDj6aEykDeb3nN15XIrujMczwHCWQX0Jpiuh+x+MUJ4O/CHhzEaZr95/JHpd4QnfPfZd8/wHZsGx8PJrs5GW7NtY69Nf/oMGAMup+b41vhLA+neprr/1e52sV+8tCquzF2u4RxY1CJvfGz/uMcVt+7mbzM7Dr6ClC9jNx6i9awd+OIncMOX3MBj2nqH3XPR40caQh9sNcFCbCVwAup/FBwMcuhQcT/e9yImRScd94GhSsVJaWqjoi8f8JHGPGEH2CzLFipZ8jRWhqMbIrJmFYpsFgFIs=
    - secure: YvRGqmO8x4fBnjhIAX9cxTxja6dFDmRCq1ZmIrPjbe3YI5UNGE58FQu6/2eMKKrvzl/a5n4kr581UyevDnjAGXz4rAayi0FDQvUc8/6XScMqaSMXRkQn3pAT1/7i/aT4Ny4Xs4+ZZxu3RFJIjjWeWZTuDTGIoBTjfvFsfehqrS3NYNO3QMHd0Hf1fyYBC6Oet3YMXmvcMp8cmzq4npsN03p0zTgPyBAD7vlJeHhnLHk8sSmEfrP1oAfzHXrsIsUppyOTBtb74OcdpvClY4hGX2894eLNn3+xJd/llFZfL71s1sermd0pmsEqCjnNP4/fw7kSJCnVSjSyBtcEvNdTDl6Lc8Uu0oIT/RoUDF7RleBy9gCYNIF7FF8k71UMhicaZLZ8TUXrPaX/6ulBYaS/GT5rba2jfidrkWWWGrh7L8gUNLf8HOXvDjSMwkdrYd5rUqvT4sHWHKmMiNx+s7pTgP43Iu1tYdqTGD1Jvj35hXVM3V3fmTwaNss6Huy7wSk65iSJyHQeV/C5W2wJf0ga+btffyYIQU9JcMug7PZX48U2xMvJRDuYwvvJ6+JH2+eCtdcwpv3qX4yEIEyjde/AVtvkcfZbMIgaiBW6DqHkz2y/k1lYQBrsdMiUuDu7seqDmky+KqHoILKkhnTLX8AnAFOdoHdr9MW5RcRGaJdF5sI=
    # GIT_USER
    - secure: PGv3LSx/cLLeXTrb482fwwecmRodboEGMXDyyONDILYU3+Ys6z60X1ORe4AmrEnegpFOPSjARLNa6L1ErJ075teAFBOldw0uK14If2IVgz4N5PaRTrJejICeeSjLRhQ3eEwghRA2fXuM6Oa0gbsNX3QbXbIPyUou5uQ4p0w3B92MYxrRXjFohIyzTE9fPCXAx5ZNa5XejQHdNMXTAigMAqliy3/Wxjf0IH9irofjh6E2lqtSVUnM3w8+yggXy8I9nQm1upn8lOQM8xU4sTusSlZIozUnYcxlsf5Z6YgoQyLlTPzNAGfgtf6BkerBeCvIXrOLtLe019bZUuWib5cn/j2xOZf/DQnnXxVe+eP8iIhbqxRR3SbdCU84FEKaJ07RK852v57So7G5Yds73qi/ArlZhvAXoV8Vww1MCq+ag++vdAF5+3Vcl+TQPJ5I5zrSRGYCMOXbUko3sPLoj7hjT0Ip122M0mzDcsRDuNY5ryy3L7qPwXmEG2fcuPAPqst2cisEco8Q4hSyh2wqmScBa4P2TGvPYBFzXTfhINcoNrXoiduc01uSB7BqcCW2Rt2qmQyqxdbDbKzhvndJ1i/4phtul6Uo5pjy8fpx9MtUKGRF3lMmz7H4kZ1Z5dSpAje9+GKrjdYy2TYvKqZTGvdIVvm/A5vTZRTkqkzFXAmxTfs=
    # GIT_PWD
    - secure: V8OQKnQhVXC4ldcrKINnpSxa7S7SN7bbdf+s9eXT1iYCeK3glu2Z4gLr4TeaifHyuKw2wvl7WGTZ+SMw14BkZFbsFDVowsvQadIH617dpL9G/ogLh8c7TK3bZk3hqnTTidgLeHo68XO22ogZyJ7QDbz+KoPv+8Tn1zW4c9nsCNNOkjJWUFk25eWNT36vlQNjJjwrv6S1wfYg6GSiF56S7N5w+ekz4PSWneP6MRrBgznUCkPBV2y3mgZShL3I/gCNoiUBsgQs/MYdM03UBNHqHKcpsF4sOv7Rj1++iNV3OPPaa9SNnLhPsolPZQ45+17j396HJrML2O3IA76hy2GYP7apsrfahP0OZBMae2tYbRVdnOIvxx9WxLsRS7SrXoNjnGlQb85DF7jXFvzV3aTCdX3J9hNWYZ9DFOr6rRJL1SJcar21nUGO6TIfxZ7M/upE2Dj6qo+xtx5p/fe4shQp4GDyL9rL3v/S1fEvA4iz/rE+6+g7cbK1zI6frpUX0uAZ68TYpgaOBCzIWLbE74yWCRUfoUOstqITzE6R/AXGiTM7M6TJ/NtB0MVBaGxMVlRhyQs0X7AyaBrDA6uCzP8OJxXec7EWLYKWV9m60ciTCUtvig3ns4Ib0ORe5hU+t4mTHEAtowHMlD7f7FQwCKdP8kvBVwLPDOsFE1IKioM/BUU=

before_cache:
    - rm -rf $HOME/.m2/repository/ch/admin/seco/alv/service/tracking
cache:
    directories:
        - "$HOME/.m2"
script:
    - export BRANCH_VERSION_SUFFIX=$([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo
        "-${TRAVIS_BRANCH//\//-}")
    - export BUILD_VERSION=$PROJECT_VERSION-build-$TRAVIS_BUILD_NUMBER$BRANCH_VERSION_SUFFIX
    - ".ci-travis/maven-set-version.sh ${BUILD_VERSION}"
deploy:
    - provider: script
      skip_cleanup: true
      script: ".ci-travis/maven-package.sh"
      on:
          all_branches: true
          condition: "$TRAVIS_BRANCH != master"
    - provider: script
      skip_cleanup: true
      script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
      on:
          branch: master
    - provider: script
      skip_cleanup: true
      script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
      on:
          all_branches: true
          condition: "$TRAVIS_BRANCH =~ ^release.*$"
notifications:
    webhooks:
        on_success: change
        on_failure: always
        on_start: never
