language: java
jdk: openjdk8
services:
  - docker
env:
  global:
    - PROJECT_VERSION=0.0.1
    - secure: Cddq9ghUuROfu/fnbdNtkDcCLAF4sIHKK7U3gxsmrAo9la2dHiBBI1G4NvVEunsEBA0fV8s5oDFL1+Y5+dA+zOwzzwSdYOLnjvoOZwV0xAC8K/MWB81wUULA4/XxTFjARl5dZwtfYqwS8t7zrx0EUxc1EAMgamtegFH7y9dv0rq2/8VDPR4NVwecqkNNm39qG4C8GsyqndtVgtzQSiRIw0H/TEz1HZwXN+V8CmovPLrUTju5Rnq8rVYf7trDTMG+z02HF1qyjLVgQFvCPxoedNqCWMjyubg4oZkmITSfTT/x+c9kVFbdz039mR8iKF3MY9XY45AFllYGtxWIc2kud1rWkierkK7I3Ki4kX5kmRtLxtO0Pz8q7nvp+ZYl+TO1g1H4syjdwrIpRQrP1M2+dnZLBZwjuywa+sExJMGTwaWNPF7z9aDH6suv2d46JHbKYDJAhIyTar5kwIrPXu942Arkudj3T4O0YsorSANlySuGQ4O7wCvJVxcCw/YxJWpBkCSd4RgD/HqFCCr1Xr8/hyw8o6MfRpNpUba4zSJPWujlSUaY2pUalugg7uJiSQKryIdACggDviooayNJalRRSRYSNlV2qedKZi2A+S17N0QClKmPvEAWEHCBOubz5ImnOV4whJcJf8hDavSXDI8Hnfw+JqZ8YLNpReuHW2hfwUo=
    - secure: Tg1hFU5r2RFYOFTbbQrfyCtJGyBdMGAb3f1NDovOdPHNB/NtI0/q7doA4S2dQSAMIVDDBcpuj3o9ayL5r5k4xGimXwk+KidCsxi6epfJyI4kB1Iq3sHxgAstmjo8kndxO/GAOItyb/06VcmirGY+HWsNwIr8Ln5VVYlW9G36GMD39ZOld4ySuqlhDr4XDPhsPgy5rTRKgdcJcihmQKqsdcGV7KzV+GlJ2lVz8NGoJrLYI05xXTVzAsZIqiWYEbU2YI3K4ItAG1S88XhQj1hcl9jZgj74LDGZOLDQgJCJNV6bOlJafiA9wL2CyNblvXytK5eNngYGL3U6MCjVD/b287ETr7Ufs0WJcl9nd4Q331bGZRE35o6SBTkL8FiKOrZvpb/lKG0ThpxzyKygAEAMLsuI4dWvOq/+cVf2jo0iq80BPKdb9gLbQI2fU1TUBnoTCAMfbt1aS3JeVnr1+eoJXGLXx6oTmSClrE6vpJWPug5LBBwcbAWMGT395VeNyTJZrqi8AyyEjl2o4W9vGy+ilaCqmzrB6JO3iWB6jGaXlaMcPWKYpxukqpGTbfmaDmtOi3vZ0l4aL7rN5W/B2gjvT6SfhkyycBpVrfwnouOyCGacGwWP6bFdJgOCnSVEegWRyHMTOop6LKdW4F6l3WQyR9TwFH/QkFucPTG4JI+QJnk=
    - secure: EQj3eO88cOyzz2jZSr1j9gdw7pxE60ntR+iZYwqBdNqoCC3z3P34the/p8i6O7f7F3Eq+xZT8hafAVqTYUlxNRyGaIAe6/aXq852gDBI6J4ddwO35tDsyMhK9ewRN98drn70lXs57KQLIML52/LxSqJaTXF2D/wwHE+c/YCVzLS/1kqbs7qaRpuicEmI7JAzEAHgOMWiokfhS+59Wf/+diP9m10jr1I2bYQyMLoUimxAjkzzrIENF0mkWQdoep6YAU0A+JC48J//6yrzHZ8AmK88Y8Y+CxVUWhqyfaC0kdDmZXRkSFFC3bgzQ7xcAhpDt/iKSRfjTtdwSYG7/59RTaYYbYtcgwCTXMaqWHaIf5p+m7CH3nHxyQ63NNJRBSzRA2aw9AiJbnWcCRbWBQjH0kuaSLPXc4RIYmbcm/vx+al+4PN/gcsYGj0WaZ0krmT0HW6t6nRwu6AOp26qbGP2BEsvn6aKovlLO8GlnoVqZ8ZkrTFtPbYeqx9Lq3OHXb0QBR/KvsVYKTka6xBL2hfu/RMeBYP7dZ0QwLGtBpAi/Nqo+aa8R+M0GVvbMcpKXjBLwGF+3aF2PmEumdiL04DhxSEa36cg9gL57z+99yUefFxl8eZwu88GAnTFQGdpJgOE9kkye5Jpn85wGENp3H9KzZ9SYo7s8WDb2hm1epjrSS0=
    - secure: IbB0o9oUEv0q+XWqLxCPLj1RmHcNy/p4NYSteHvEYqxB2BJc7Y3cCYbvdXkNBKFUSepTuC+pz/1974x3Wi9oQhHy9GsKa1uLwx5m/+yEP3soI+rReSGxbyDyV8KmcsAT+wfUNa9WeDp9mM7xSZtzE2+NQPAqSZgVSD8rxCnzSUL5vxizTuAt95PqFoBdYGU2yccFItSCxioftuuPwEw3xz2RUilQO91iuE3jzNHMBDUNudx1ypC7svicwo5cAINTQDAI9xBx3XFDgFKUIhFST4oJHQn8eMhN8gdPT6lDsrPnxG1PMVJUSecfwEcF8JxbpzjSnSSMupiEfDoPZNbRHbi+LD5qxAnE2BFTHdIJtF/RwNAh5btRwFkaRVQ0hhrUgqyD9OK0koyecWjj0YK36whczvwfF9CND1mjD+rGGf/nTQY3ZoATKKtcqBDl0jjff0OAKnKlHi5b5+bqBwG4J93PCIfRK+ERjjQdpKCWENMHTKUyVnjV54+cNgsBArhas0XJ/2SngrFDZufVaZ6lsNGeVFJKrppGmvu8ni5evUn0x88UWoEp73dBDU+pRgESkNfNeDc5sWNOdltfX1gJr9eeelw3/5fp8W/J+pakh9lragVHcVASKs2XaC8j9RtM1o+XGZ1VSqseH/sPlJ9NDUHTUHQVFAlJgwnSzKFWG18=
before_cache:
  - rm -rf $HOME/.m2/repository/ch/admin/seco/alv/service/tracking
cache:
  directories:
    - "$HOME/.m2"
script:
  - export BRANCH_VERSION_SUFFIX=$([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo
    "-${TRAVIS_BRANCH//\//-}")
  - export BUILD_VERSION=$PROJECT_VERSION-build-$TRAVIS_BUILD_NUMBER$BRANCH_VERSION_SUFFIX
  - ".ci-travis/maven-set-version.sh ${BUILD_VERSION}"
install:
  - "./mvnw --settings ./.mvn/wrapper/settings.xml install -DskipTests=true"
deploy:
  - provider: script
    skip_cleanup: true
    script: ".ci-travis/maven-package.sh"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != master"
  - provider: script
    skip_cleanup: true
    script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ".ci-travis/maven-deploy.sh ${ARTIFACTORY_USERNAME} ${ARTIFACTORY_PASSWORD}
    && .ci-travis/push-version-bump.sh ${BUILD_VERSION} ${GIT_USER} ${GIT_PWD}"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^release.*$"
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never
