os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.9.4"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
env:
  global:
    - NODE_VERSION=8.9.4
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - ARTIFACTORY_USERNAME=travis
    - ARTIFACTORY_PASSWORD=F5r72onFlWtY
    - SONARQUBE_LOGIN=0737a751397d2b05b3bab2e13f1ec63632698928
before_install:
  - git fetch --unshallow || true
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
script:
  - chmod +x gradlew
  - ./gradlew clean check
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: "./gradlew bootJar publish -Pprod -Pzipkin -Pversion=${TRAVIS_JOB_NUMBER}-SNAPSHOT -x test --stacktrace && curl https://dev.job-room.ch:8443/deploy/jr2 --insecure"
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: "./gradlew bootJar publish -Pprod -Pzipkin -Pversion=${TRAVIS_JOB_NUMBER}-SNAPSHOT -x test --stacktrace && curl https://dev.job-room.ch:8443/deploy/jr2 --insecure"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^release.*$"
  - provider: script
    skip_cleanup: true
    script: "./gradlew bootJar publish -Pprod -Pzipkin -Pversion=${TRAVIS_TAG} -x test --stacktrace"
    on:
      tags: true
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # default: false
