server:
    port: 8080

spring:
    jpa:
        properties:
            hibernate.jdbc.lob.non_contextual_creation: true
    liquibase:
        change-log: classpath:/liquibase/master.xml
        enabled: true

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always

info:
    project:
        version: @project.version@
